### ISSUE TITLE
SQLAdmin intercepts dynamic path params.

### ISSUE THREAD

**Issue by cemrehancavdar** [peterschutt/sqladmin-litestar-plugin#11]
Hey @peterschutt,

Admin intercepts dynamic path params as "Not Found" 
If you add admin to plugins "/dynamic/{name:int}" won't work.

This repo has an mvce to check:
https://github.com/cemrehancavdar/sqladmin-plugin-mvce

**Comment by peterschutt** [comment]
All this plugin does is add a `@asgi` handler to `/`, and the MCVE doesn't involve this plugin at all:

```py
from litestar import Litestar, asgi, get
from litestar.types.asgi_types import Receive, Scope, Send


@get("/")
async def home() -> str:
    return "Hello, world!"


@asgi("/", is_mount=True)
async def mounted(scope: Scope, receive: Receive, send: Send) -> None:
    await send({"type": "http.response.start", "status": 200})
    await send({"type": "http.response.body", "body": b"Mounted!"})


@get("/dynamic/{name:int}")
async def dynamic(name: int) -> str:
    return f"Hello, {name}!"

app = Litestar([home, dynamic, mounted])
```

You should raise it over at litestar.

**Comment by ryanolf-tb** [comment]
@peterschutt Could a workaround here be to mount under a path like "/admin" and avoid conflicts? I tried that briefly but the admin interface doesn't render quite right, so some additional tweaks (not sure where) are needed. But it seems like it could work.
