### ISSUE TITLE
/admin does not work when using Granian Plugin

### ISSUE THREAD

**Issue by sorasful** [peterschutt/sqladmin-litestar-plugin#44]
Hi, 

I've been trying to add SQLAdmin to my project thanks to this plugin, but I got an 500 error with not much detail when I tried to reach `/admin` route.

So I tried to disable the Granian plugin and use Uvicorn instead, and now it works.

I thought it could be good to report this, in case someone else also stumble on this.

**Comment by peterschutt** [comment]
Hi @sorasful - thanks for reporting this.

I'm working my way back from an unplanned extended break - so catching up on the work side of things at the moment. I will get to this when the time is right, but if you can provide any more info, especially a reproduction repository that I can clone and run would be great. If not, no problem either.

**Comment by sorasful** [comment]
Hmm, actually, I tried to get started with a minimal example and it seems to be working. Maybe something else is messing around in my setup. 

If I can reproduce I'll reopen with an example to reproduce. Thanks for your time and efforts.
